F = "032022"
Z = "012120121"
L = "30102021"
U = "08102021"
B = "20112021"
AMM = "072022"
VB = "13122021"
VP = "13022022"
VNL = "112022"
OD = "280522"
BK = "08022023"
CACAO = "12/09/2021"
S = "200421"
FIN = "-"
PEP = "230420"
LIM = "31122021"
AR = "31122021"
CNL = "31628"
CH = "-"
MAND = "062022"
LB = "170822"
FI = "20002524"
SEM = "112021"
FG = "-"
FO = "-"
MIE = "31122022"
CIOC = "03112022"
F_CER = "26052022"
F_CURC = "16032022"
OLIVE = "03819/17"
ROSM = "30/06/23"
F_SEN = "868/816"
Z_CAN = "-"
VBIO = "-"
VNC = "30/07/2026"
UVA = "01/10/22"
FIC = "01/10/22"
COT = "01/10/22"

friselline_olio = {"F": F, "OD": OD, "LB": LB, "S": S}
taralli_olio = {"F": F, "OD": OD, "LB": LB, "S": S}
grissini_olio = {"F": F, "OD": OD, "LB": LB, "S": S}
crostini_olio = {"F": F, "OD": OD, "LB": LB, "S": S}
friselline_peperoncino = {"F": F, "OD": OD, "LB": LB, "S": S, "PEP": PEP}
friselline_integrali = {"F": F, "FI": FI, "OD": OD, "LB": LB, "S": S}
friselline_cereali = {"F": F, "F_CER": F_CER, "OD": OD, "LB": LB, "S": S}
friselline_curcuma = {"F": F, "F_CURC": F_CURC, "OD": OD, "LB": LB, "S": S}
grissini_olive = {"F": F, "OD": OD, "LB": LB, "S": S, "OLIVE": OLIVE}
taralli_finocchio = {"F": F, "OD": OD, "LB": LB, "S": S, "FIN": FIN}
taralli_cereali = {"F": F, "F_CER": F_CER, "OD": OD, "LB": LB, "S": S}
grissini_integrali = {"F": F, "FI": FI, "OD": OD, "LB": LB, "S": S}
crostini_integrali = {"F": F, "FI": FI, "OD": OD, "LB": LB, "S": S}
crostini_rosmarino = {"F": F, "OD": OD, "LB": LB, "S": S, "ROSM": ROSM}
frise_orzo = {"F": F, "FO": FO, "FI": FI, "S": S, "LB": LB}
frise_grano = {"SEM": SEM, "LB": LB, "S": S}
friselline_senatore = {"F": F, "F_SEN": F_SEN, "OD": OD, "LB": LB, "S": S}
sfoglie_cereali = {"F": F, "F_CER": F_CER, "OD": OD, "LB": LB, "S": S}
sfoglie_curcuma = {"F": F, "F_CURC": F_CURC, "OD": OD, "LB": LB, "S": S}
biscotti_salute = {"F": F, "Z": Z, "U": U, "L": L, "BK": BK, "B": B, "LIM": LIM, "VNL": VNL}
biscotti_mandorla = {"F": F, "Z": Z, "U": U, "L": L, "BK": BK, "B": B, "LIM": LIM, "VNL": VNL, "MAND": MAND}
tocchetti_vino = {"F": F, "Z": Z, "BK": BK, "VNL": VNL, "VP": VP, "OD": OD}
tocchetti_cioccolato = {"F": F, "Z": Z, "BK": BK, "VNL": VNL, "VP": VP, "OD": OD, "CIOC": CIOC}
taralli_primitivo = {"F": F, "Z": Z, "BK": BK, "VNL": VNL, "VP": VP, "OD": OD}
taralli_biologico = {"F": F, "Z": Z, "BK": BK, "VNL": VNL, "VBIO": VBIO, "OD": OD}
taralli_bianco = {"F": F, "Z": Z, "BK": BK, "VNL": VNL, "VB": VB, "OD": OD}
paste_casarecce = {"F": F, "Z": Z, "OD": OD, "L": L, "U": U, "AMM": AMM, "LIM": LIM, "VNL": VNL}
taralli_vincotto = {"F": F, "Z": Z, "OD": OD, "VB": VB, "VNC": VNC, "BK": BK, "VNL": VNL}
treccine_vino = {"F": F, "Z": Z, "BK": BK, "VNL": VNL, "VP": VP, "OD": OD, "MAND": MAND}
mustazzoli = {"F": F, "Z": Z, "MAND": MAND, "B": B, "L": L, "U": U, "CH": CH, "CNL": CNL, "AMM": AMM, "CACAO": CACAO, "AR": AR}
mustaccere_cioccolato = {"F": F, "Z": Z, "OD": OD, "CACAO": CACAO, "MAND": MAND, "AMM": AMM, "AR": AR, "CNL": CNL, "CH": CH}
pitteddhe = {"F": F, "Z": Z, "B": B, "U": U, "MIE": MIE, "SEM": SEM, "BK": BK, "VNL": VNL, "LIM": LIM, "UVA": UVA, "FIC": FIC, "COT": COT}
crostata = {"F": F, "Z": Z, "B": B, "U": U, "MIE": MIE, "SEM": SEM, "BK": BK, "VNL": VNL, "LIM": LIM, "UVA": UVA, "FIC": FIC, "COT": COT}
paste_mandorla = {"MAND": MAND, "Z": Z, "U": U, "MIE": MIE, "LIM": LIM, "VNL": VNL}
frollini_cereali = {"F": F, "F_CER": F_CER, "OD": OD, "U": U, "MIE": MIE, "BK": BK, "VNL": VNL, "LIM": LIM, "SEM": SEM}
mustaccere_glassate = {"F": F, "Z": Z, "OD": OD, "MAND": MAND, "AMM": AMM, "AR": AR, "CNL": CNL, "CH": CH}
frollini = {"F": F, "SEM": SEM, "OD": OD, "U": U, "MIE": MIE, "BK": BK, "VNL": VNL, "LIM": LIM}
mezzelune_mandorla = {"F": F, "Z": Z, "U": U, "L": L, "BK": BK, "B": B, "LIM": LIM, "VNL": VNL, "MAND": MAND}
mezzelune_cioccolato = {"F": F, "Z": Z, "U": U, "L": L, "BK": BK, "B": B, "LIM": LIM, "VNL": VNL, "CIOC": CIOC}

